### ISSUE TITLE
Howto enable for markdown?

### ISSUE THREAD

**Issue by v217** [divinites/LatexEquationPreview#2]
Can I enable this for markup other than latex, eg markdown by specifying the delimiters?  Thanks!

**Comment by divinites** [comment]
That is a good suggestion, I will try to update a new version that has this feature. Thanks.

**Comment by divinites** [comment]
One problem, this plug-in use scope to find the equation region, could you please tell me which syntax file you are using for markdown? Thanks.

**Comment by v217** [comment]
I use [Github flavored markdown](https://guides.github.com/features/mastering-markdown/) with $-delimiters. Thank you
PS: Do you know if there is a similar sublimetext-phantom plugin for imagepreview in markdown?

**Comment by divinites** [comment]
Hi, I am afraid that GFM does not work with the plug-in at this moment, since when I use $-delimiters in GFM Markdown, the sublime text scope of the equation becomes:
```
text.html.markdown.gfm meta.paragraph.markdown 
```
which cannot differentiate the euqation itself with other text, while this plug-in heavily relies on scope matching techniques to identify the border of the equation. 

I did not notice any phantom plugin for imagepreview, but I think that developing such a plug-in won't be more difficult than this one, since it is pretty straightforward. Phantom really opens a new gate in sublime text plug-in development.

**Comment by divinites** [comment]
https://packagecontrol.io/packages/MarkdownLivePreview  here is a markdown live preview plug-in
